knife4j:
  enable: false
  setting:
    language: zh_cn
spring:
  profiles:
    active: local
  application:
    name: shifen-backend
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/shifen
    username: root
    password: 123456

server:
  port: 8080

shifen:
  info:
    version: 1.0.0
    base-package: com.coder.shifen
